[package]
name = "carakistan"
version = "0.1.0"
authors = ["littlecastrum <littlecastrum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.14.0"
rand = "0.6.5"